### ISSUE TITLE
[TICKER] was not predicted.

### ISSUE THREAD

**Issue by windowshopr** [Lucas-Kohorst/Python-Stock#2]
Tried running the program today (Nov 18) and it was not able to predict any of the 200 tickers. Maybe it could be looked at again? This was what I received...

```
DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)

DevTools listening on ws://127.0.0.1:61162/devtools/browser/7694dcc8-39a2-4b3f-b66b-7ca684aa9750
[461812:462804:1118/171456.153:ERROR:shader_disk_cache.cc(257)] Failed to create shader cache entry: -2
[461812:462804:1118/171456.154:ERROR:shader_disk_cache.cc(257)] Failed to create shader cache entry: -2
[461812:462804:1118/171456.155:ERROR:shader_disk_cache.cc(257)] Failed to create shader cache entry: -2
Number: 0
WFT
Stock: WFT was not predicted
Number: 1
RAD
Stock: RAD was not predicted
Number: 2
QEP
Stock: QEP was not predicted
Number: 3
UPL
Stock: UPL was not predicted
Number: 4
LADR
Stock: LADR was not predicted
.....
```

**Comment by Lucas-Kohorst** [comment]
Did you make sure to install all of the correct imports properly?

**Comment by windowshopr** [comment]
Yes, all requirements are installed. It pulls the list of stocks from the website correctly, however it just seems to be stuck when it comes to the prediction bit.

I tried just changing the start date to be a little more recent just to try, but same issue. I'm running python 3 if that matters. Let me know if you have any suggestions. Thanks!

**Comment by Lucas-Kohorst** [comment]
Does the code reach the part where it takes the tickers and creates a .csv file with the historical data?

**Comment by windowshopr** [comment]
No, fair point. No .csv file is made.

**Comment by windowshopr** [comment]
...however I do have the latest install of iexfinance, if that helps.

**Comment by Lucas-Kohorst** [comment]
Interesting. So that means that the historical data was never retrieved? Can you run a get_historical_data in another script to see if it works?

**Comment by windowshopr** [comment]
Yes, I will try to separate it and see if I can get_historical_data using just one ticker to see what’s going on. Hopefully can get it to work, otherwise will have to find a different way of getting historical data to .csv, but I’ll try it when I get home tonight and let you know.

**Comment by windowshopr** [comment]
Oh pff. I've isolated the problem. Smacks forehead in shame.

You just need to make a folder in the root directory of the script named "Exports" before running, or better still, implement this code:

```
#Outputting the Historical data into a .csv for later use
df = get_historical_data(stock, start=start, end=end, output_format='pandas')
if os.path.exists('./Exports'):
    csv_name = ('Exports/' + stock + '_Export.csv')
else:
    os.mkdir("Exports")
    csv_name = ('Exports/' + stock + '_Export.csv')
df.to_csv(csv_name)
df['prediction'] = df['close'].shift(-1)
df.dropna(inplace=True)
```

The script as it stands now won't make the directory for you if it doesn't exist already. This addition will alleviate that using the already imported os.

All works fine now! Thanks!

**Comment by windowshopr** [comment]
Oh, and just another thing to add. If you're using Gmail as your email address for the app, you may need to enable the "Allow less secure apps" option in your security settings to allow the script access to your account before it'll send the email > text to your phone.

**Comment by Lucas-Kohorst** [comment]
Ah yes, you are right about the Gmail part and about the folder needing to be created. If you submit this as a pull request I will merge it into the master.
