### ISSUE TITLE
When ran, everything goes well EXCEPT that I get this message: [TICKER] was not predicted..

### ISSUE THREAD

**Issue by aaronllowe** [Lucas-Kohorst/Python-Stock#4]
This script works up until it starts predicting. It prints to terminal that [ticker] was not predicted. Why is this happening? And also, can you predict other stocks, like the S&P 500? Please help me! I also see an `Exports` folder, with all the [ticker]_Export.csv files.
Here is the output: 
Number: 0
BRS
Stock: BRS was not predicted
Number: 1
JCP
Stock: JCP was not predicted
Number: 2
XON
Stock: XON was not predicted
Number: 3
DNR
Stock: DNR was not predicted
Number: 4
AKS
Stock: AKS was not predicted
Number: 5
ESV
Stock: ESV was not predicted
Number: 6
WTW
Stock: WTW was not predicted
Number: 7
NE
Stock: NE was not predicted
Number: 8
SNH
Stock: SNH was not predicted
Number: 9
PEI
Stock: PEI was not predicted
Number: 10
CPE
Stock: CPE was not predicted
Number: 11
TXMD
Stock: TXMD was not predicted
Number: 12
CDE
Stock: CDE was not predicted
Number: 13
HMY
Stock: HMY was not predicted
Number: 14
CRZO
Stock: CRZO was not predicted
Number: 15
AVP
Stock: AVP was not predicted
Number: 16
AG
Stock: AG was not predicted
Number: 17
LTHM
Stock: LTHM was not predicted
Number: 18
TVTY
Stock: TVTY was not predicted
Number: 19
GCI
Stock: GCI was not predicted
Number: 20
IRWD
Stock: IRWD was not predicted
Number: 21
SPN
Stock: SPN was not predicted
Number: 22
MUX
Stock: MUX was not predicted
Number: 23
AKRX
Stock: AKRX was not predicted
Number: 24
TLGT
Stock: TLGT was not predicted
Number: 25
ANF
Stock: ANF was not predicted
Number: 26
HOLI
Stock: HOLI was not predicted
Number: 27
LBRT
Stock: LBRT was not predicted
Number: 28
DFRG
Stock: DFRG was not predicted
Number: 29
DBD
Stock: DBD was not predicted
Number: 30
LL
Stock: LL was not predicted
Number: 31
MRC
Stock: MRC was not predicted
Number: 32
NVRO
Stock: NVRO was not predicted
Number: 33
FET
Stock: FET was not predicted
Number: 34
BOOT
Stock: BOOT was not predicted
Number: 35
OBE
Stock: OBE was not predicted
Number: 36
WTI
Stock: WTI was not predicted
Number: 37
EPE
Stock: EPE was not predicted
Number: 38
ABR
Stock: ABR was not predicted
Number: 39
HOME
Stock: HOME was not predicted
Number: 40
SEMG
Stock: SEMG was not predicted
Number: 41
INVA
Stock: INVA was not predicted
Number: 42
PDS
Stock: PDS was not predicted
Number: 43
BLDR
Stock: BLDR was not predicted
Number: 44
NEW
Stock: NEW was not predicted
Number: 45
FNKO
Stock: FNKO was not predicted
Number: 46
AIMT
Stock: AIMT was not predicted
Number: 47
QUOT
Stock: QUOT was not predicted
Number: 48
ELY
Stock: ELY was not predicted
Number: 49
CSIQ
Stock: CSIQ was not predicted
Number: 50
CCS
Stock: CCS was not predicted
Number: 51
RCII
Stock: RCII was not predicted
Number: 52
EGO
Stock: EGO was not predicted
Number: 53
MGNX
Stock: MGNX was not predicted
Number: 54
CBAY
Stock: CBAY was not predicted
Number: 55
ASMB
Stock: ASMB was not predicted
Number: 56
HCC
Stock: HCC was not predicted
Number: 57
EAT
Stock: EAT was not predicted
Number: 58
JKS
Stock: JKS was not predicted
Number: 59
SCS
Stock: SCS was not predicted
Number: 60
ACRS
Stock: ACRS was not predicted
Number: 61
GLOG
Stock: GLOG was not predicted
Number: 62
FOE
Stock: FOE was not predicted
Number: 63
TTMI
Stock: TTMI was not predicted
Number: 64
ATRA
Stock: ATRA was not predicted
Number: 65
SGRY
Stock: SGRY was not predicted
Number: 66
CRCM
Stock: CRCM was not predicted
Number: 67
FORM
Stock: FORM was not predicted
Number: 68
PLCE
Stock: PLCE was not predicted
Number: 69
BFR
Stock: BFR was not predicted
Number: 70
OR
Stock: OR was not predicted
Number: 71
SOI
Stock: SOI was not predicted
Number: 72
FBC
Stock: FBC was not predicted
Number: 73
MNTA
Stock: MNTA was not predicted
Number: 74
CASA
Stock: CASA was not predicted
Number: 75
PLAB
Stock: PLAB was not predicted
Number: 76
SFLY
Stock: SFLY was not predicted
Number: 77
VSTO
Stock: VSTO was not predicted
Number: 78
QNST
Stock: QNST was not predicted
Number: 79
ECHO
Stock: ECHO was not predicted
Number: 80
SFUN
Stock: SFUN was not predicted
Number: 81
RMBS
Stock: RMBS was not predicted
Number: 82
QHC
Stock: QHC was not predicted
Number: 83
MMLP
Stock: MMLP was not predicted
Number: 84
WDR
Stock: WDR was not predicted
Number: 85
IRTC
Stock: IRTC was not predicted
Number: 86
MEDP
Stock: MEDP was not predicted
Number: 87
ANGO
Stock: ANGO was not predicted
Number: 88
ARA
Stock: ARA was not predicted
Number: 89
ITCI
Stock: ITCI was not predicted
Number: 90
HCLP
Stock: HCLP was not predicted
Number: 91
PMT
Stock: PMT was not predicted
Number: 92
TRVG
Stock: TRVG was not predicted
Number: 93
KOPN
Stock: KOPN was not predicted
Number: 94
HASI
Stock: HASI was not predicted
Number: 95
CONN
Stock: CONN was not predicted
Number: 96
TGI
Stock: TGI was not predicted
Number: 97
BPFH
Stock: BPFH was not predicted
Number: 98
INGN
Stock: INGN was not predicted
Number: 99
SCWX
Stock: SCWX was not predicted
Number: 100
BCRX
Stock: BCRX was not predicted
Number: 101
PATK
Stock: PATK was not predicted
Number: 102
CEIX
Stock: CEIX was not predicted
Number: 103
MCRN
Stock: MCRN was not predicted
Number: 104
CRNT
Stock: CRNT was not predicted
Number: 105
TIVO
Stock: TIVO was not predicted
Number: 106
LPSN
Stock: LPSN was not predicted
Number: 107
HSC
Stock: HSC was not predicted
Number: 108
VIOT
Stock: VIOT was not predicted
Number: 109
BSIG
Stock: BSIG was not predicted
Number: 110
GPMT
Stock: GPMT was not predicted
Number: 111
LTC
Stock: LTC was not predicted
Number: 112
SCVL
Stock: SCVL was not predicted
Number: 113
ENVA
Stock: ENVA was not predicted
Number: 114
BAS
Stock: BAS was not predicted
Number: 115
MXL
Stock: MXL was not predicted
Number: 116
CTMX
Stock: CTMX was not predicted
Number: 117
CBPX
Stock: CBPX was not predicted
Number: 118
MHLD
Stock: MHLD was not predicted
Number: 119
WGO
Stock: WGO was not predicted
Number: 120
ATEN
Stock: ATEN was not predicted
Number: 121
NCI
Stock: NCI was not predicted
Number: 122
CMP
Stock: CMP was not predicted
Number: 123
CHSP
Stock: CHSP was not predicted
Number: 124
SDRL
Stock: SDRL was not predicted
Number: 125
ZUMZ
Stock: ZUMZ was not predicted
Number: 126
ECPG
Stock: ECPG was not predicted
Number: 127
BPT
Stock: BPT was not predicted
Number: 128
JMEI
Stock: JMEI was not predicted
Number: 129
BCOR
Stock: BCOR was not predicted
Number: 130
PPBI
Stock: PPBI was not predicted
Number: 131
KMDA
Stock: KMDA was not predicted
Number: 132
WSR
Stock: WSR was not predicted
Number: 133
CALA
Stock: CALA was not predicted
Number: 134
AHT
Stock: AHT was not predicted
Number: 135
KLIC
Stock: KLIC was not predicted
Number: 136
MMI
Stock: MMI was not predicted
Number: 137
ATKR
Stock: ATKR was not predicted
Number: 138
OEC
Stock: OEC was not predicted
Number: 139
ALEC
Stock: ALEC was not predicted
Number: 140
HUBG
Stock: HUBG was not predicted
Number: 141
MTH
Stock: MTH was not predicted
Number: 142
UVV
Stock: UVV was not predicted
Number: 143
ATSG
Stock: ATSG was not predicted
Number: 144
CTRL
Stock: CTRL was not predicted
Number: 145
FSS
Stock: FSS was not predicted
Number: 146
FCF
Stock: FCF was not predicted
Number: 147
LGIH
Stock: LGIH was not predicted
Number: 148
ANAB
Stock: ANAB was not predicted
Number: 149
VECO
Stock: VECO was not predicted
Number: 150
GWB
Stock: GWB was not predicted
Number: 151
LXFR
Stock: LXFR was not predicted
Number: 152
JNCE
Stock: JNCE was not predicted
Number: 153
OIA
Stock: OIA was not predicted
Number: 154
VRNS
Stock: VRNS was not predicted
Number: 155
ENTA
Stock: ENTA was not predicted
Number: 156
SA
Stock: SA was not predicted
Number: 157
PGTI
Stock: PGTI was not predicted
Number: 158
EGY
Stock: EGY was not predicted
Number: 159
LRN
Stock: LRN was not predicted
Number: 160
MERC
Stock: MERC was not predicted
Number: 161
TTI
Stock: TTI was not predicted
Number: 162
LZB
Stock: LZB was not predicted
Number: 163
TGS
Stock: TGS was not predicted
Number: 164
SGH
Stock: SGH was not predicted
Number: 165
DGII
Stock: DGII was not predicted
Number: 166
WLH
Stock: WLH was not predicted
Number: 167
IMAX
Stock: IMAX was not predicted
Number: 168
MDC
Stock: MDC was not predicted
Number: 169
SIMO
Stock: SIMO was not predicted
Number: 170
OFG
Stock: OFG was not predicted
Number: 171
INAP
Stock: INAP was not predicted
Number: 172
BRKL
Stock: BRKL was not predicted
Number: 173
FRTA
Stock: FRTA was not predicted
Number: 174
FGP
Stock: FGP was not predicted
Number: 175
CDR
Stock: CDR was not predicted
Number: 176
ARCH
Stock: ARCH was not predicted
Number: 177
AVAV
Stock: AVAV was not predicted
Number: 178
ORTX
Stock: ORTX was not predicted
Number: 179
MEI
Stock: MEI was not predicted
Number: 180
KRNY
Stock: KRNY was not predicted
Number: 181
IBP
Stock: IBP was not predicted
Number: 182
VHI
Stock: VHI was not predicted
Number: 183
CORE
Stock: CORE was not predicted
Number: 184
SCHN
Stock: SCHN was not predicted
Number: 185
VRA
Stock: VRA was not predicted
Number: 186
NM
Stock: NM was not predicted
Number: 187
ENZ
Stock: ENZ was not predicted
Number: 188
EIG
Stock: EIG was not predicted
Number: 189
ASC
Stock: ASC was not predicted
Number: 190
USNA
Stock: USNA was not predicted
Number: 191
MED
Stock: MED was not predicted
Number: 192
SSTK
Stock: SSTK was not predicted
Number: 193
RMED
Stock: RMED was not predicted
Number: 194
UMH
Stock: UMH was not predicted
Number: 195
MCC
Stock: MCC was not predicted
Number: 196
ABCB
Stock: ABCB was not predicted
Number: 197
BMCH
Stock: BMCH was not predicted
Number: 198
PAR
Stock: PAR was not predicted
Number: 199
KEYW
Stock: KEYW was not predicted

**Comment by ohalligan** [comment]
I have the same issue

**Comment by mprzydatek** [comment]
Did any of you guys has managed to fix it?

**Comment by mprzydatek** [comment]
OK, i found the problem. Because of the too-broad 'except' clause in the code (the one that prints "Stock ... was not predicted" message), an error from IEX library is suppressed, that says: "The IEX Cloud API key must be provided either through the token variable or through the environmental variable IEX_TOKEN.". Now everything's clear.

**Comment by ankitatanmay** [comment]
> OK, i found the problem. Because of the too-broad 'except' clause in the code (the one that prints "Stock ... was not predicted" message), an error from IEX library is suppressed, that says: "The IEX Cloud API key must be provided either through the token variable or through the environmental variable IEX_TOKEN.". Now everything's clear.

Hey, can you write correct code here ?

**Comment by atulbhingarde** [comment]
can we add exception and message that indicates what is happening with the token (specifically if it is not set ) ?

**Comment by Shashankv3** [comment]
I still have this error, does anyone have the functional code?

**Comment by rodi055** [comment]
I found the you had to have an authentication token for the "IEX Cloud" API, but this service is not free.
